### PR TITLE
Adds maven support to the project

### PR DESCRIPTION
**Pull request by SKrPl**
Solves issue: https://github.com/loklak/loklak_jlib_api/issues/8

### CODE REVIEW

**Review by vibhcool — CHANGES_REQUESTED** [review]
maven project builds perfectly 👍 ,
 please also add some docs in readme about how to build like that of ant

**Comment by SKrPl** [comment]
@vibhcool Added documentation on using **Maven** for building and testing.

**Review by vibhcool — APPROVED** [review]
LGTM

**Review by djmgit — APPROVED** [review]
Looks good to me

**Pull request merged**
